import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ClipboardCheck, Plus, RefreshCw, UserRound, X } from 'lucide-react'
import { api } from '../lib/api'
import { confirmDanger } from '../lib/danger'
import './WorkboardPage.css'

const FALLBACK_STATUSES = ['backlog', 'active', 'review', 'done']
const COPY = {
  en: {
    eyebrow: 'Decision workflow', title: 'Workboard', desc: 'Define the outcome, let the agent propose evidence, then approve or return with direction.',
    newItem: 'New decision contract', itemTitle: 'Title', titleHint: 'What work needs a reviewed decision?', outcome: 'Required outcome', outcomeHint: 'What must be true when this is complete?', criteria: 'Acceptance criteria', criteriaHint: 'One verifiable criterion per line', owner: 'Owner', ownerHint: 'Team or person (optional)', risk: 'Risk',
    create: 'Add contract', refresh: 'Refresh', loading: 'Loading workboard...', empty: 'No items in this stage.', error: 'Workboard could not be loaded.', retry: 'Try again', backlog: 'Backlog', active: 'Active', review: 'Review', done: 'Done', low: 'Low', medium: 'Medium', high: 'High', noOwner: 'Unassigned', items: n => `${n} ${n === 1 ? 'item' : 'items'}`,
    confirmCreate: 'Persist this decision contract?', confirmCommand: action => `Apply ${action} to this work item?`, close: 'Close details', contract: 'Decision contract', proposal: 'Agent proposal', evidence: 'Evidence', timeline: 'Decision timeline', revision: 'Revision', noProposal: 'No proposal submitted yet.', instructions: 'Return instructions', start: 'Start work', submit: 'Submit for review', approve: 'Approve decision', return: 'Return with direction', proposalHint: 'Summarize the proposed result', evidenceLabel: 'Evidence label', evidenceDetail: 'What was verified and where?', returnHint: 'State what must change before resubmission',
  },
  zh: {
    eyebrow: '\u51b3\u7b56\u6d41\u7a0b', title: '\u5de5\u4f5c\u770b\u677f', desc: '\u5148\u5b9a\u4e49\u7ed3\u679c\uff0c\u518d\u7531 Agent \u63d0\u4ea4\u8bc1\u636e\uff0c\u6700\u540e\u6279\u51c6\u6216\u5e26\u65b9\u5411\u9000\u56de\u3002',
    newItem: '\u65b0\u5efa\u51b3\u7b56\u5951\u7ea6', itemTitle: '\u6807\u9898', titleHint: '\u4ec0\u4e48\u5de5\u4f5c\u9700\u8981\u5ba1\u6838\u51b3\u7b56\uff1f', outcome: '\u5fc5\u8981\u7ed3\u679c', outcomeHint: '\u5b8c\u6210\u65f6\u5fc5\u987b\u6210\u7acb\u4ec0\u4e48\uff1f', criteria: '\u9a8c\u6536\u6807\u51c6', criteriaHint: '\u6bcf\u884c\u4e00\u6761\u53ef\u9a8c\u8bc1\u6807\u51c6', owner: '\u8d1f\u8d23\u4eba', ownerHint: '\u56e2\u961f\u6216\u4e2a\u4eba\uff08\u53ef\u9009\uff09', risk: '\u98ce\u9669',
    create: '\u6dfb\u52a0\u5951\u7ea6', refresh: '\u5237\u65b0', loading: '\u6b63\u5728\u52a0\u8f7d...', empty: '\u8be5\u9636\u6bb5\u6682\u65e0\u9879\u76ee\u3002', error: '\u5de5\u4f5c\u770b\u677f\u52a0\u8f7d\u5931\u8d25\u3002', retry: '\u91cd\u8bd5', backlog: '\u5f85\u529e', active: '\u6267\u884c\u4e2d', review: '\u5f85\u5ba1\u6838', done: '\u5df2\u5b8c\u6210', low: '\u4f4e', medium: '\u4e2d', high: '\u9ad8', noOwner: '\u672a\u5206\u914d', items: n => `${n} \u9879`,
    confirmCreate: '\u786e\u8ba4\u6301\u4e45\u5316\u8be5\u51b3\u7b56\u5951\u7ea6\uff1f', confirmCommand: action => `\u786e\u8ba4\u6267\u884c ${action}\uff1f`, close: '\u5173\u95ed\u8be6\u60c5', contract: '\u51b3\u7b56\u5951\u7ea6', proposal: 'Agent \u63d0\u6848', evidence: '\u8bc1\u636e', timeline: '\u51b3\u7b56\u65f6\u95f4\u7ebf', revision: '\u4fee\u8ba2', noProposal: '\u5c1a\u672a\u63d0\u4ea4\u63d0\u6848\u3002', instructions: '\u9000\u56de\u6307\u4ee4', start: '\u5f00\u59cb\u6267\u884c', submit: '\u63d0\u4ea4\u5ba1\u6838', approve: '\u6279\u51c6\u51b3\u7b56', return: '\u5e26\u65b9\u5411\u9000\u56de', proposalHint: '\u6982\u62ec\u5efa\u8bae\u7ed3\u679c', evidenceLabel: '\u8bc1\u636e\u540d\u79f0', evidenceDetail: '\u9a8c\u8bc1\u4e86\u4ec0\u4e48\uff0c\u4f4d\u4e8e\u54ea\u91cc\uff1f', returnHint: '\u8bf4\u660e\u91cd\u65b0\u63d0\u4ea4\u524d\u5fc5\u987b\u4fee\u6539\u7684\u5185\u5bb9',
  },
}

export default function WorkboardPage({ lang = 'en' }) {
  const text = COPY[lang] || COPY.en
  const [items, setItems] = useState([]), [statuses, setStatuses] = useState(FALLBACK_STATUSES)
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [busy, setBusy] = useState('')
  const [selectedID, setSelectedID] = useState('')
  const [form, setForm] = useState({ title: '', outcome: '', criteria: '', owner: '', risk: 'low' })
  const [decision, setDecision] = useState({ proposal: '', evidenceLabel: '', evidenceDetail: '', note: '' })
  const selected = items.find(item => item.id === selectedID)
  const load = useCallback(async () => { setLoading(true); setError(''); try { const data = await api('/api/workboard'); setItems(data?.items || []); setStatuses(data?.statuses?.length ? data.statuses : FALLBACK_STATUSES) } catch (err) { setError(err.message || text.error) } finally { setLoading(false) } }, [text.error])
  useEffect(() => { load() }, [load])
  const grouped = useMemo(() => Object.fromEntries(statuses.map(s => [s, items.filter(i => i.status === s)])), [items, statuses])
  const create = async e => { e.preventDefault(); if (!confirmDanger('workboard_create', text.confirmCreate)) return; setBusy('create'); setError(''); try { const item = await api('/api/workboard', { method: 'POST', dangerous: true, body: JSON.stringify({ title: form.title, outcome: form.outcome, acceptance_criteria: form.criteria.split(/\r?\n/).map(v => v.trim()).filter(Boolean), owner: form.owner, risk: form.risk }) }); setItems(v => [...v, item]); setForm({ title: '', outcome: '', criteria: '', owner: '', risk: 'low' }) } catch (err) { setError(err.message) } finally { setBusy('') } }
  const command = async (item, action, extra = {}) => { if (!confirmDanger(`workboard_${action}`, text.confirmCommand(action))) return; setBusy(item.id); setError(''); try { const updated = await api(`/api/workboard/${item.id}/commands`, { method: 'POST', dangerous: true, body: JSON.stringify({ action, expected_revision: item.revision, ...extra }) }); setItems(v => v.map(x => x.id === updated.id ? updated : x)); setDecision({ proposal: '', evidenceLabel: '', evidenceDetail: '', note: '' }) } catch (err) { setError(err.message) } finally { setBusy('') } }
  const submit = e => { e.preventDefault(); command(selected, 'submit_proposal', { proposal: decision.proposal, evidence: [{ label: decision.evidenceLabel, detail: decision.evidenceDetail }] }) }
  const returnItem = e => { e.preventDefault(); command(selected, 'return', { note: decision.note }) }

  return <section className="workboard-page">
    <header className="workboard-intro"><div><p className="workboard-eyebrow"><ClipboardCheck size={15}/>{text.eyebrow}</p><h2>{text.title}</h2><p>{text.desc}</p></div><button className="workboard-refresh" type="button" onClick={load} disabled={loading}><RefreshCw size={16}/>{text.refresh}</button></header>
    <form className="workboard-create" onSubmit={create}><strong><Plus size={15}/>{text.newItem}</strong><label><span>{text.itemTitle}</span><input required maxLength={160} value={form.title} placeholder={text.titleHint} onChange={e => setForm({...form, title:e.target.value})}/></label><label><span>{text.outcome}</span><textarea required maxLength={1000} value={form.outcome} placeholder={text.outcomeHint} onChange={e => setForm({...form, outcome:e.target.value})}/></label><label><span>{text.criteria}</span><textarea required value={form.criteria} placeholder={text.criteriaHint} onChange={e => setForm({...form, criteria:e.target.value})}/></label><label><span>{text.owner}</span><input maxLength={80} value={form.owner} placeholder={text.ownerHint} onChange={e => setForm({...form, owner:e.target.value})}/></label><label><span>{text.risk}</span><select value={form.risk} onChange={e => setForm({...form, risk:e.target.value})}>{['low','medium','high'].map(r => <option key={r} value={r}>{text[r]}</option>)}</select></label><button type="submit" disabled={busy === 'create'}><Plus size={16}/>{text.create}</button></form>
    {error && <div className="workboard-error" role="alert"><AlertTriangle size={17}/><span>{error}</span>{!items.length && <button type="button" onClick={load}>{text.retry}</button>}</div>}
    {loading ? <div className="workboard-state" role="status">{text.loading}</div> : <div className="workboard-columns">{statuses.map(status => <section className={`workboard-column is-${status}`} key={status}><header><div><span className="workboard-status-mark"/><h3>{text[status] || status}</h3></div><span>{text.items(grouped[status]?.length || 0)}</span></header><div className="workboard-stack">{(grouped[status] || []).map(item => <button type="button" className="workboard-card" key={item.id} onClick={() => setSelectedID(item.id)}><span className="workboard-card-top"><span className={`workboard-risk is-${item.risk}`}>{item.risk === 'high' && <AlertTriangle size={12}/>} {text[item.risk] || item.risk}</span><code>r{item.revision}</code></span><strong>{item.title}</strong><span><UserRound size={14}/>{item.owner || text.noOwner}</span><small>{item.outcome}</small></button>)}{!grouped[status]?.length && <p className="workboard-empty">{text.empty}</p>}</div></section>)}</div>}
    {selected && <div className="workboard-overlay" role="presentation" onMouseDown={e => e.target === e.currentTarget && setSelectedID('')}><aside className="workboard-detail" role="dialog" aria-modal="true" aria-labelledby="workboard-detail-title"><header><div><span className={`workboard-risk is-${selected.risk}`}>{text[selected.risk]}</span><h3 id="workboard-detail-title">{selected.title}</h3><p>{text.revision} {selected.revision} · {text[selected.status]}</p></div><button type="button" aria-label={text.close} onClick={() => setSelectedID('')}><X size={18}/></button></header><section><h4>{text.contract}</h4><p>{selected.outcome}</p><ul>{selected.acceptance_criteria?.map((criterion, i) => <li key={i}>{criterion}</li>)}</ul></section>{selected.instructions && <section className="workboard-instructions"><h4>{text.instructions}</h4><p>{selected.instructions}</p></section>}<section><h4>{text.proposal}</h4><p>{selected.proposal?.summary || text.noProposal}</p>{selected.proposal?.evidence?.length > 0 && <dl>{selected.proposal.evidence.map((e, i) => <div key={i}><dt>{e.label}</dt><dd>{e.detail}</dd></div>)}</dl>}</section><DecisionActions item={selected} text={text} busy={busy === selected.id} decision={decision} setDecision={setDecision} command={command} submit={submit} returnItem={returnItem}/><section><h4>{text.timeline}</h4><ol className="workboard-timeline">{[...(selected.events || [])].reverse().map((event, i) => <li key={`${event.revision}-${i}`}><strong>{event.action}</strong><span>{event.actor} · r{event.revision}</span>{event.note && <p>{event.note}</p>}</li>)}</ol></section></aside></div>}
  </section>
}

function DecisionActions({ item, text, busy, decision, setDecision, command, submit, returnItem }) {
  if (item.status === 'backlog') return <button className="workboard-primary" type="button" disabled={busy} onClick={() => command(item, 'start')}>{text.start}</button>
  if (item.status === 'active') return <form className="workboard-decision" onSubmit={submit}><label><span>{text.proposal}</span><textarea required value={decision.proposal} placeholder={text.proposalHint} onChange={e => setDecision({...decision, proposal:e.target.value})}/></label><div><label><span>{text.evidenceLabel}</span><input required value={decision.evidenceLabel} onChange={e => setDecision({...decision, evidenceLabel:e.target.value})}/></label><label><span>{text.evidenceDetail}</span><input required value={decision.evidenceDetail} onChange={e => setDecision({...decision, evidenceDetail:e.target.value})}/></label></div><button className="workboard-primary" type="submit" disabled={busy}>{text.submit}</button></form>
  if (item.status === 'review') return <div className="workboard-review-actions"><button className="workboard-primary" type="button" disabled={busy} onClick={() => command(item, 'approve', { note: decision.note })}>{text.approve}</button><form onSubmit={returnItem}><label><span>{text.return}</span><textarea required value={decision.note} placeholder={text.returnHint} onChange={e => setDecision({...decision, note:e.target.value})}/></label><button type="submit" disabled={busy}>{text.return}</button></form></div>
  return null
}
