import { readFileSync } from 'node:fs'
import { describe, expect, test } from 'vitest'

const source = readFileSync('src/ChatApp.jsx', 'utf8')

describe('session-scoped guided-message queue wiring', () => {
  test('clears stale queue immediately, then applies the selected session backend queue', () => {
    const openStart = source.indexOf('const openSession = async')
    const clearQueue = source.indexOf('applyQueueSnapshot([])', openStart)
    const fetchSession = source.indexOf('const d = await chatApi(`/api/chat/session/${id}`)', openStart)
    const restoreQueue = source.indexOf('applyQueueSnapshot(d.queued_messages, d.id)', openStart)
    expect(openStart).toBeGreaterThan(-1)
    expect(clearQueue).toBeGreaterThan(openStart)
    expect(fetchSession).toBeGreaterThan(clearQueue)
    expect(restoreQueue).toBeGreaterThan(fetchSession)
  })

  test('clears both queue state and ref when switching instances', () => {
    const switchStart = source.indexOf('const switchChatInstance =')
    const switchEnd = source.indexOf('\n  }', switchStart)
    const switchSource = source.slice(switchStart, switchEnd)
    expect(switchSource).toContain('applyQueueSnapshot([])')
    expect(switchSource).not.toContain('setQueuedMessages([])')
  })

  test('serializes atomic queue operations and applies backend responses', () => {
    expect(source).toContain("method:'PATCH'")
    expect(source).toContain('body:JSON.stringify({ op:operation, ...payload })')
    expect(source).not.toContain('body:JSON.stringify({ operation, ...payload })')
    expect(source).toContain('const d = await api(queueURL)')
    expect(source).toContain('applyQueueSnapshot(d.queued_messages, sessionId)')
    expect(source.match(/queueWriteRef\.current = request/g)?.length).toBeGreaterThanOrEqual(2)
    expect(source).not.toContain('body:JSON.stringify({ messages:snapshot })')
  })

  test('guiding projects the user turn immediately, then attaches to the backend-started run', () => {
    const guideStart = source.indexOf('const guideQueued = async')
    const optimisticUser = source.indexOf('id:`guided-${next.id}`', guideStart)
    const restoreFollow = source.indexOf('setFollowState(true)', optimisticUser)
    const optimisticProjection = source.indexOf('setMessages(xs => isActiveSession(id)', restoreFollow)
    const guideTry = source.indexOf('    try {', optimisticProjection)
    const abortPendingAssistant = source.indexOf("const pendingAssistantIndex = xs.findLastIndex(message => message.role === 'assistant' && !message.content)", guideTry)
    const guideURL = source.indexOf('const guideURL = `/api/chat/guide/${id}/${next.id}`', guideTry)
    const firstGuide = source.indexOf('let guideResult = await chatApi(guideURL', guideURL)
    const queuedCheck = source.indexOf("if (guideResult?.status === 'queued')", firstGuide)
    const cancel = source.indexOf('await chatApi(`/api/chat/cancel/${id}`', queuedCheck)
    const retryGuide = source.indexOf('guideResult = await chatApi(guideURL', cancel)
    const startedCheck = source.indexOf("if (guideResult?.status !== 'started')", retryGuide)
    const markStarted = source.indexOf('guideStarted = true', startedCheck)
    const activeCheck = source.indexOf('if (!isActiveSession(id)) return', markStarted)
    const refreshGuided = source.indexOf('await refreshQueue(id)', activeCheck)
    const reconnect = source.indexOf('await attachRunningStream(id, { waitForRun:true })', refreshGuided)
    const rollback = source.indexOf('if (!guideStarted && guidedUser)', reconnect)
    const releaseGuiding = source.indexOf('if (guidingQueueRef.current === next.id)', rollback)
    const resetRun = source.indexOf('activeRunRef.current = false', releaseGuiding)
    const guideEnd = source.indexOf('\n  }', resetRun)
    const guideFinally = source.slice(source.lastIndexOf('} finally {', resetRun), guideEnd)
    expect(guideStart).toBeGreaterThan(-1)
    expect(optimisticUser).toBeGreaterThan(guideStart)
    expect(restoreFollow).toBeGreaterThan(optimisticUser)
    expect(optimisticProjection).toBeGreaterThan(restoreFollow)
    expect(guideTry).toBeGreaterThan(optimisticProjection)
    expect(abortPendingAssistant).toBeGreaterThan(guideTry)
    expect(abortPendingAssistant).toBeLessThan(guideURL)
    expect(guideURL).toBeGreaterThan(guideTry)
    expect(firstGuide).toBeGreaterThan(guideURL)
    expect(queuedCheck).toBeGreaterThan(firstGuide)
    expect(cancel).toBeGreaterThan(queuedCheck)
    expect(retryGuide).toBeGreaterThan(cancel)
    expect(startedCheck).toBeGreaterThan(retryGuide)
    expect(markStarted).toBeGreaterThan(startedCheck)
    expect(activeCheck).toBeGreaterThan(markStarted)
    expect(refreshGuided).toBeGreaterThan(activeCheck)
    expect(reconnect).toBeGreaterThan(refreshGuided)
    expect(rollback).toBeGreaterThan(reconnect)
    expect(releaseGuiding).toBeGreaterThan(rollback)
    expect(resetRun).toBeGreaterThan(releaseGuiding)
    expect(resetRun).toBeLessThan(guideEnd)
    expect(guideFinally).not.toContain('setBusy(false)')
    expect(guideFinally).not.toContain("setStreamingSid('')")
  })

  test('reloads the active session only after cancel persistence completes', () => {
    const cancelStart = source.indexOf('const cancelRun = async')
    const abort = source.indexOf('streamAbortRef.current?.abort?.()', cancelStart)
    const persisted = source.indexOf('await chatApi(`/api/chat/cancel/${id}`', abort)
    const activeCheck = source.indexOf('if (isActiveSession(id)) await openSession(id, false)', persisted)
    const cancelEnd = source.indexOf('\n  }', activeCheck)
    expect(cancelStart).toBeGreaterThan(-1)
    expect(abort).toBeGreaterThan(cancelStart)
    expect(persisted).toBeGreaterThan(abort)
    expect(activeCheck).toBeGreaterThan(persisted)
    expect(activeCheck).toBeLessThan(cancelEnd)
  })

  test('releases local run admission before post-run session reloads', () => {
    const runStart = source.indexOf('const runSend = async')
    const terminalFinally = source.indexOf('if (runToken !== runSeqRef.current) return', runStart)
    const releaseRun = source.indexOf('activeRunRef.current = false', terminalFinally)
    const releaseBusy = source.indexOf('setBusy(false)', releaseRun)
    const releaseStreaming = source.indexOf("setStreamingSid('')", releaseBusy)
    const reloadSessions = source.indexOf('const refreshedSessions = await loadSessions(id)', terminalFinally)
    const reloadSession = source.indexOf('await openSession(id, false)', reloadSessions)
    expect(terminalFinally).toBeGreaterThan(runStart)
    expect(releaseRun).toBeGreaterThan(terminalFinally)
    expect(releaseBusy).toBeGreaterThan(releaseRun)
    expect(releaseStreaming).toBeGreaterThan(releaseBusy)
    expect(reloadSessions).toBeGreaterThan(releaseStreaming)
    expect(reloadSession).toBeGreaterThan(reloadSessions)
  })

  test('refreshes the backend queue only after a guided send has an active session', () => {
    const runStart = source.indexOf('const runSend = async')
    const activeCheck = source.indexOf('} else if (!isActiveSession(id)) {', runStart)
    const refreshGuided = source.indexOf('await refreshQueue(id)', activeCheck)
    expect(runStart).toBeGreaterThan(-1)
    expect(activeCheck).toBeGreaterThan(runStart)
    expect(refreshGuided).toBeGreaterThan(activeCheck)
  })

  test('does not replace an optimistic guided turn with a heartbeat snapshot', () => {
    const refreshStart = source.indexOf('const refreshList = async')
    const attach = source.indexOf('void attachRunningStream(activeID, { waitForRun:true })', refreshStart)
    const guardedSnapshot = source.indexOf('} else if (!guidingQueueRef.current && shouldRefreshChatSnapshot(before, after)) {', attach)
    const refreshSnapshot = source.indexOf('void refreshActiveSessionSnapshot(activeID)', guardedSnapshot)
    expect(refreshStart).toBeGreaterThan(-1)
    expect(attach).toBeGreaterThan(refreshStart)
    expect(guardedSnapshot).toBeGreaterThan(attach)
    expect(refreshSnapshot).toBeGreaterThan(guardedSnapshot)
  })

  test('uses SSE invalidation with authoritative GET and polling fallback', () => {
    const eventsURL = source.indexOf('`/api/chat/queue/${sid}/events`')
    const eventSource = source.indexOf('new EventSource(eventsURL)', eventsURL)
    const ready = source.indexOf("source.addEventListener('ready', syncQueue)", eventSource)
    const changed = source.indexOf("source.addEventListener('queue_changed', syncQueue)", ready)
    const fallback = source.lastIndexOf('window.setInterval(syncQueue, 3000)', eventsURL)
    const calibration = source.indexOf('window.setInterval(syncQueue, 60000)', eventSource)
    const cleanup = source.indexOf('source?.close()', calibration)
    expect(eventsURL).toBeGreaterThan(-1)
    expect(fallback).toBeGreaterThan(-1)
    expect(fallback).toBeLessThan(eventsURL)
    expect(eventSource).toBeGreaterThan(eventsURL)
    expect(ready).toBeGreaterThan(eventSource)
    expect(changed).toBeGreaterThan(ready)
    expect(calibration).toBeGreaterThan(changed)
    expect(cleanup).toBeGreaterThan(calibration)
  })
})
