import { readFileSync } from 'node:fs'
import { describe, expect, test } from 'vitest'

const source = readFileSync('src/ChatApp.jsx', 'utf8')

describe('session-scoped guided-message queue wiring', () => {
  test('clears stale queue immediately, then restores the selected session queue', () => {
    const openStart = source.indexOf('const openSession = async')
    const clearQueue = source.indexOf("syncQueue([], { persist:false })", openStart)
    const fetchSession = source.indexOf('const d = await chatApi(`/api/chat/session/${id}`)', openStart)
    const restoreQueue = source.indexOf("syncQueue(Array.isArray(d.queued_messages) ? d.queued_messages : [], { persist:false })", openStart)
    expect(openStart).toBeGreaterThan(-1)
    expect(clearQueue).toBeGreaterThan(openStart)
    expect(fetchSession).toBeGreaterThan(clearQueue)
    expect(restoreQueue).toBeGreaterThan(fetchSession)
  })

  test('clears both queue state and ref when switching instances', () => {
    const switchStart = source.indexOf('const switchChatInstance =')
    const switchEnd = source.indexOf('\n  }', switchStart)
    const switchSource = source.slice(switchStart, switchEnd)
    expect(switchSource).toContain("syncQueue([], { persist:false })")
    expect(switchSource).not.toContain('setQueuedMessages([])')
  })

  test('serializes full queue snapshots to the session API', () => {
    expect(source).toContain("`/api/chat/queue/${sessionId}`")
    expect(source).toContain("queueWriteRef.current = queueWriteRef.current")
    expect(source).toContain("body:JSON.stringify({ messages:snapshot })")
  })

  test('guiding attaches to the backend-started run for live updates', () => {
    const guideStart = source.indexOf('const guideQueued = async')
    const guideURL = source.indexOf('const guideURL = `/api/chat/guide/${id}/${next.id}`', guideStart)
    const firstGuide = source.indexOf('let guideResult = await chatApi(guideURL', guideURL)
    const queuedCheck = source.indexOf("if (guideResult?.status === 'queued')", firstGuide)
    const cancel = source.indexOf('await chatApi(`/api/chat/cancel/${id}`', queuedCheck)
    const retryGuide = source.indexOf('guideResult = await chatApi(guideURL', cancel)
    const startedCheck = source.indexOf("if (guideResult?.status !== 'started')", retryGuide)
    const activeCheck = source.indexOf('if (!isActiveSession(id)) return', startedCheck)
    const removeGuided = source.indexOf('syncQueue(queuedRef.current.filter(x => x.id !== next.id)', activeCheck)
    const clearGuidingRef = source.indexOf("guidingQueueRef.current = ''", removeGuided)
    const clearGuidingState = source.indexOf("setGuidingQueueId('')", clearGuidingRef)
    const optimisticUser = source.indexOf('id:`guided-${next.id}`', clearGuidingState)
    const reconnect = source.indexOf('await attachRunningStream(id, { waitForRun:true })', optimisticUser)
    const resetRun = source.indexOf('activeRunRef.current = false', reconnect)
    const guideEnd = source.indexOf('\n  }', reconnect)
    const guideFinally = source.slice(source.lastIndexOf('} finally {', resetRun), guideEnd)
    expect(guideStart).toBeGreaterThan(-1)
    expect(guideURL).toBeGreaterThan(guideStart)
    expect(firstGuide).toBeGreaterThan(guideURL)
    expect(queuedCheck).toBeGreaterThan(firstGuide)
    expect(cancel).toBeGreaterThan(queuedCheck)
    expect(retryGuide).toBeGreaterThan(cancel)
    expect(startedCheck).toBeGreaterThan(retryGuide)
    expect(activeCheck).toBeGreaterThan(startedCheck)
    expect(removeGuided).toBeGreaterThan(activeCheck)
    expect(clearGuidingRef).toBeGreaterThan(removeGuided)
    expect(clearGuidingState).toBeGreaterThan(clearGuidingRef)
    expect(optimisticUser).toBeGreaterThan(clearGuidingState)
    expect(reconnect).toBeGreaterThan(optimisticUser)
    expect(resetRun).toBeGreaterThan(reconnect)
    expect(resetRun).toBeLessThan(guideEnd)
    expect(guideFinally).not.toContain('setBusy(false)')
    expect(guideFinally).not.toContain("setStreamingSid('')")
  })

  test('reloads the active session only after cancel persistence completes', () => {
    const cancelStart = source.indexOf('const cancelRun = async')
    const abort = source.indexOf('streamAbortRef.current?.abort?.()', cancelStart)
    const persisted = source.indexOf('await chatApi(`/api/chat/cancel/${id}`', abort)
    const activeCheck = source.indexOf('if (isActiveSession(id)) await openSession(id, false)', persisted)
    const cancelEnd = source.indexOf('\n  }', activeCheck)
    expect(cancelStart).toBeGreaterThan(-1)
    expect(abort).toBeGreaterThan(cancelStart)
    expect(persisted).toBeGreaterThan(abort)
    expect(activeCheck).toBeGreaterThan(persisted)
    expect(activeCheck).toBeLessThan(cancelEnd)
  })

  test('removes a guided item only after a send has an active session', () => {
    const runStart = source.indexOf('const runSend = async')
    const activeCheck = source.indexOf('} else if (!isActiveSession(id)) {', runStart)
    const removeGuided = source.indexOf('syncQueue(queuedRef.current.filter(x => x.id !== guidedQueueId)', runStart)
    expect(runStart).toBeGreaterThan(-1)
    expect(activeCheck).toBeGreaterThan(runStart)
    expect(removeGuided).toBeGreaterThan(activeCheck)
  })
})
