import { useState } from 'react'
import { Eye, Play, Square } from 'lucide-react'

export function Stat({ label, value, icon }) { return <div className="stat"><div>{icon}</div><span>{label}</span><b>{value}</b></div> }
export function Panel({ title, children, className = '' }) { return <div className={`panel ${className}`}><div className="panel-title">{title}</div>{children}</div> }
export function EntryList({ items = [], empty }) { return <div className="entry-list">{items.length ? items.map((e, i) => <div className="entry" key={`${e.path || e.name}-${i}`}><b>{e.name || e.path}</b><span>{e.path}{e.kind ? ` · ${e.kind}` : ''}{e.size ? ` · ${e.size} B` : ''}</span></div>) : <p className="muted">{empty}</p>}</div> }
export function ServiceRow({ svc, onStart, onStop, onLogs, onAutostart, t }) { return <div className="service-card"><div><b>{svc.name}</b><span title={svc.command?.join(' ')}>{svc.command?.join(' ')}</span><em>{svc.kind}{svc.pid ? ` · PID ${svc.pid}` : ''}</em></div><div className={svc.running ? 'ok' : 'err'}>{svc.running ? t.running : t.stopped}</div><div className="svc-actions"><button disabled={svc.running} onClick={() => onStart(svc.name)}><Play size={14}/>{t.start}</button><button disabled={!svc.running} onClick={() => onStop(svc.name)}><Square size={14}/>{t.stop}</button><button onClick={() => onLogs?.(svc.name)}><Eye size={14}/>{t.logs}</button><label className="toggle-inline"><input type="checkbox" checked={!!svc.autostart} onChange={e => onAutostart?.(svc.name, e.target.checked)} />{t.autostartService}</label></div></div> }
export function ChannelServiceTable({ services = [], onStart, onStop, onLogs, onAutostart, t }) { return <div className="channel-table-wrap"><table className="channel-table"><thead><tr><th>{t.fields?.name || 'Name'}</th><th>{t.fields?.status || 'Status'}</th><th>PID</th><th>{t.fields?.command || 'Command'}</th><th>{t.autostart}</th><th>{t.actions || 'Actions'}</th></tr></thead><tbody>{services.length ? services.map(svc => <tr key={svc.name}><td><b>{svc.name}</b><small>{svc.kind}</small></td><td><span className={svc.running ? 'status-pill running' : 'status-pill stopped'}>{svc.running ? t.running : t.stopped}</span></td><td>{svc.pid || '-'}</td><td><code title={svc.command?.join(' ')}>{svc.command?.join(' ') || '-'}</code></td><td><label className="toggle-inline table-toggle"><input type="checkbox" checked={!!svc.autostart} onChange={e => onAutostart?.(svc.name, e.target.checked)} />{svc.autostart ? t.enabled : t.disabled}</label></td><td><div className="svc-actions table-actions"><button disabled={svc.running} onClick={() => onStart(svc.name)}><Play size={14}/>{t.start}</button><button disabled={!svc.running} onClick={() => onStop(svc.name)}><Square size={14}/>{t.stop}</button><button onClick={() => onLogs?.(svc.name)}><Eye size={14}/>{t.logs}</button></div></td></tr>) : <tr><td colSpan="6" className="empty-cell">{t.hints.noFrontend}</td></tr>}</tbody></table></div> }
export function SecretInput({ value, onChange, t }) { const [show, setShow] = useState(false); return <div className="secret-row"><input type={show ? 'text' : 'password'} value={value || ''} placeholder={t.hints.savedSecret} onChange={e => onChange(e.target.value)} /><button type="button" onClick={() => setShow(!show)}>{show ? t.hide : t.show}</button></div> }
